version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  api:
    build: 
      context: ../src
      dockerfile: TimeTracker.Api/Dockerfile
    environment:
      ConnectionStrings__TimeTrackerDb: Host=database;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD
    ports:
      - 5040:80
    depends_on:
      - database

volumes:
  database-data: